### ISSUE TITLE
Random graph models

### ISSUE THREAD

**Issue by gdalle** [gdalle/InternsINDY2024#3]
Starting a literature review on realistic models for random graphs.

Reading list:

- [Flatland-RL : Multi-Agent Reinforcement Learning on Trains](https://arxiv.org/abs/2012.05893) - the original design we will try to simplify
- [Spatial networks - Barthelemy](https://doi.org/10.1016/j.physrep.2010.11.002)
- [Networks, M. Newman](https://academic.oup.com/book/27884) (get the PDF from LibGen)

Assignment:

- Start thinking about the features that make railway networks unique

**Comment by AntoineBut** [comment]
**Parallel Graphs in Julia : Proposition de plan** 


Implémentation de certaines primitives nécessaires à de nombreux algorithmes parallèles, potentiellement dans utils.jl : 
Reduce : déjà implémenté
Scan
Filter
EdgeMap & VertexMap


Implémentation d’un premier algorithme complet 
Low-Diameter Decomposition (utilisé dans de nombreux autres algorithmes)
Parallel speed-up benchmark (en plus des tests de correctness)

Implémentation d’un second algorithme plus complexe 
Graph Coloring (NP-Hard)
Benchmarks : random input, worst-case input (on peut s’attendre à une large différence)
Comparaison des résultats obtenus et des garanties théoriques, analyse statistique
